apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-prod
  namespace: core
spec:
  project: default
  source:
    repoURL: 'https://github.com/martcklm/argocd-gitops.git'
    targetRevision: master
    path: infrastructure/gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: java-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
