apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-java-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/gitops-repo.git'
    targetRevision: master
    path: infrastructure/gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-java-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
