steps:
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'package']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'REGION-docker.pkg.dev/PROJECT_ID/java-app/image:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'REGION-docker.pkg.dev/PROJECT_ID/java-app/image:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['kustomize', 'build', 'k8s/', '-o', 'app.yaml']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'app.yaml', 'gs://your-artifact-bucket/app.yaml']

images:
- 'REGION-docker.pkg.dev/PROJECT_ID/java-app/image:$COMMIT_SHA'
