steps:
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'package']

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - -c
    - |
      sed -i "s|IMAGE_TAG|$COMMIT_SHA|g" k8s/deployment.yaml

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-poc/argocd-poc/java-app/image:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-poc/argocd-poc/java-app/image:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['kustomize', 'build', 'k8s/', '-o', 'app.yaml']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'app.yaml', 'gs://argocd-poc-manifests/app.yaml']

images:
- 'us-central1-docker.pkg.dev/gcp-poc/argocd-poc/java-app/image:$COMMIT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY
