kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: us-central1-docker.pkg.dev/gcp-poc-466408/gcp-poc/java-app:latest
