apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  template:
    spec:
      containers:
      - name: java-app
        image: us-central1-docker.pkg.dev/gcp-poc-466408/gcp-poc/java-app:latest
